### ISSUE TITLE
mailto awesome should give error for spaces in mailto link.

### ISSUE THREAD

**Issue by Raza403** [fulldecent/html-proofer-mailto_awesome#11]
When I ran awesome mailto link in "https://validator.nu" I received a bad value error `Space is not allowed`. Found standard procedure is to convert space into`%20`.
mailto_awesome should show an error if `space` is present in mailto link.
Screenshot of validator.nu:
![1](https://user-images.githubusercontent.com/20680336/62757681-94272e80-ba95-11e9-85a9-234a4e3398b1.png)

**Comment by fulldecent** [comment]
Out of scope. Spaces in an HTML attribute is an HTML error not a mailto awesome error.

Referring to upstream https://github.com/gjtorikian/html-proofer/pull/362
