### ISSUE TITLE
Make this this best possible example for html-proofer

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-proofer-mailto_awesome#2]
@gjtorikian please assist with item 1 here.

Before pushing to RubyGems, I would like to ensure this simple project meets the highest quality standards. Because then we will create more custom tests and I hope to publish this one on a new wiki at the [html-proofer project](https://github.com/gjtorikian/html-proofer).

- [x] Decide on the correct gem name
   * I know that underscores versus dashes are very important but I have read information:
     * Source: http://guides.rubygems.org/name-your-gem/ tells me maybe to choose `html-proofer-mailto_awesome` but this will put it in the `html/proofer/mailto_awesome` namespace. Compare to http://www.rubydoc.info/gems/html-proofer/HTMLProofer/Check which is in the `HTMLProofer/` namespace. 
  - [x] Confirm this repository is named using best practices -- how can I confirm it is?
- [x] Implement tests using spec
  - [x] Add Travis CI testing
- [x] Follow `bundle gem` project format (minus `bin/` directory)
    * Discussion: is this best practice?
- [x] Publish to rubygems (@fulldecent to do this)
- [x] Publish to html-proofer wiki with discussion

**Comment by gjtorikian** [comment]
Which item should I assist with?

**Comment by fulldecent** [comment]
@gjtorikian Could you please advise what the preferred "Ruby name" is I should use for this project? 

What we currently have is `html-proofer-mailto-awesome` in https://github.com/fulldecent/html-proofer-mailto-awesome/blob/master/html-proofer-mailto-awesome.gemspec

Should there be underscores in there instead? Perhaps `html-proofer-mailto_awesome` or `html_proofer-mailto_awesome`?

Also, if you have any other advice on this work plan, please let me know. I intend to publish this on a html-proofer wiki, so hopefully everyone will follow the lead here.

**Comment by fulldecent** [comment]
@ilyalyo Please help with adding spec testing and adding a travis CI file. And also a Travis build badge on the README.

**Comment by gjtorikian** [comment]
Dashes are definitely the convention in Ruby, so I believe `html-proofer-mailto_awesome` is what you want to go for here.

The rest of the plan looks great!

**Comment by fulldecent** [comment]
Thank you, I figured out how to get this on ruby gems. We are live!
