### ISSUE TITLE
Make travis CI work

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-proofer-mailto_awesome#4]
I have no idea why it is broken

**Comment by ilyalyo** [comment]
Fixed. This line: 
cache: bundler 
was the main reason.

**Comment by fulldecent** [comment]
[![Build Status](https://travis-ci.org/fulldecent/html-proofer-mailto_awesome.svg?branch=master)](https://travis-ci.org/fulldecent/html-proofer-mailto_awesome)

Looks great, thanks!
