### ISSUE TITLE
Fix Gemspec error for latest Ruby

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-proofer-mailto_awesome#9]
New Ruby broke this gemspec

See https://travis-ci.org/fulldecent/html-proofer-mailto_awesome/builds/232872815

This gem was originally created a while ago, recommend to create a new gem from scratch to see the new recommended template.

**Comment by fulldecent** [comment]
@raza403 requesting help here

**Comment by Raza403** [comment]
@fulldecent OK I'll see it.

**Comment by fulldecent** [comment]
@Raza403 ping

**Comment by fulldecent** [comment]
@Raza403 pushed a new version
